---
  name: NORM AND FLAGS CHECKS

  on:
    push:
      branches:
        - '*'
    pull_request:
      branches:
        - '*'

  jobs:
    # check-norm:
    #   runs-on: ubuntu-latest
    #   steps:
    #     - name: Checkout code
    #       uses: actions/checkout@v2

    #     - name: Set up Python
    #       uses: actions/setup-python@v2
    #       with:
    #         python-version: 3.12

    #     - name: Install dependencies
    #       run: |
    #         pip install setuptools norminette

    #     - name: Run norminette checks
    #       run: |
    #         norminette

    make-with-flags:
      runs-on: ubuntu-latest
      # needs: check-norm
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: install docker-compose
          run: |
            sudo apt-get update
            sudo apt-get install -y make gcc

        - name: Create Makefile for testing
          run: |
            echo -e 'SRCS= $(shell find . -type f -name "*.c")\nINCLUDES= -Iinclude\nOBJS= $(SRCS:.c=.o)\nDEPS= $(SRCS:.c=.d)\nCC= cc\nCFLAGS= -Wall -Wextra -Werror\nDEPSFLAGS= -MMD -MP\nNAME= uniq_name_][\nall: $(NAME)\n$(NAME): $(OBJS)\n\t$(CC) $(OBJS) -o $(NAME)\n%.o: %.c\n\t$(CC) $(CFLAGS) $(DEPSFLAGS) $(INCLUDES) -c $< -o $@\n-include $(DEPS)' > Makefile
        - name: Run Services
          run: |
            make
